# Generated by Django 4.1.7 on 2023-04-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BikeAds',
            new_name='BikeAd',
        ),
    ]
