# Generated by Django 4.1.7 on 2023-04-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_bikeads_bikead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikead',
            old_name='bikebrand',
            new_name='bike_brand',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikediscription',
            new_name='bike_discription',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikeenginesize',
            new_name='bike_engine_size',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikefueltanksize',
            new_name='bike_fueltank_size',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikewithabs',
            new_name='bike_has_abs',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikeimage',
            new_name='bike_image',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikemileage',
            new_name='bike_mileage',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikename',
            new_name='bike_name',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikerentprice',
            new_name='bike_rent_price',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='biketopspeed',
            new_name='bike_topspeed',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='biketype',
            new_name='bike_type',
        ),
        migrations.RenameField(
            model_name='bikead',
            old_name='bikeweight',
            new_name='bike_weight',
        ),
    ]
